local Package = require("lpm-core.package")
local Config = require("lpm-core.config")

local fs = require("fs")
local env = require("env")
local path = require("path")
local rocked = require("rocked")

--- Finds the first *.rockspec file in `dir`, returns its path or nil.
---@param dir string
---@return string?
local function findRockspec(dir)
	local iter = fs.readdir(dir)
	if not iter then return nil end
	for entry in iter do
		if entry.type == "file" and entry.name:match("%.rockspec$") then
			return path.join(dir, entry.name)
		end
	end
	return nil
end

--- Finds a free suffix for a file that already exists, e.g. init_.lua, init__.lua, ...
---@param dir string
---@param basename string  e.g. "init"
---@param ext string       e.g. ".lua"
---@return string          free filename (basename only, not full path)
local function freeSuffixName(dir, basename, ext)
	local suffix = "_"
	while true do
		local name = basename .. suffix .. ext
		if not fs.exists(path.join(dir, name)) then
			return name
		end
		suffix = suffix .. "_"
	end
end

--- Builds a buildfn for a rockspec-based package.
--- The buildfn receives the output dir (already populated with the src copy).
--- It renames any existing init.lua then writes a new one that sets up
--- package.preload for every module declared in the rockspec's build.modules.
---@param rockData rocked.raw.Output
---@return fun(outDir: string)
local function makeRockspecBuildfn(rockData)
	return function(outDir)
		-- Rename existing init.lua if present
		local origName = nil ---@type string?
		local initPath = path.join(outDir, "init.lua")
		if fs.exists(initPath) then
			origName = freeSuffixName(outDir, "init", ".lua")
			fs.move(initPath, path.join(outDir, origName))
		end

		-- Build the preload lines for each declared module
		local lines = {}
		local build = rockData.build

		-- modules table maps module-name → source file (or build source table)
		-- We only handle the string (file path) form here; C source tables are skipped.
		if build and build.modules then
			for modname, src in pairs(build.modules) do
				if type(src) == "string" then
					-- Normalise separator: rockspecs use '/', always
					local relpath = src:gsub("\\", "/")
					-- Strip a leading "src/" prefix that some rocks use, since the
					-- output dir already contains the src contents.
					relpath = relpath:gsub("^src/", "")
					lines[#lines + 1] = string.format(
						"package.preload[%q] = function(...) return dofile(dir .. %q) end",
						modname,
						"/" .. relpath
					)
				end
			end
		end

		-- Also register entries from build.install.lua if present (builtin type)
		if build and build.install and build.install.lua then
			for modname, src in pairs(build.install.lua) do
				if type(src) == "string" then
					local relpath = src:gsub("\\", "/"):gsub("^src/", "")
					lines[#lines + 1] = string.format(
						"package.preload[%q] = function(...) return dofile(dir .. %q) end",
						modname,
						"/" .. relpath
					)
				end
			end
		end

		local preloadBlock = table.concat(lines, "\n")

		local origBlock = ""
		if origName then
			origBlock = string.format("\ndofile(dir .. %q)", "/" .. origName)
		end

		local initContent = string.format([[
-- Generated by lpm from rockspec: %s %s
local dir = debug.getinfo(1, "S").source:match("^@(.+)/[^/]+$") or "."
%s%s
]], rockData.package or "?", rockData.version or "?", preloadBlock, origBlock)

		fs.write(initPath, initContent)
	end
end

--- Opens a directory that contains a *.rockspec file (and no lpm.json).
--- Parses the rockspec and returns a Package with a synthetic config and a
--- buildfn that generates a wrapper init.lua with package.preload entries.
---@param dir string?
---@return lpm.Package?, string?
local function openRocks(dir)
	dir = dir or env.cwd()

	local rockspecPath = findRockspec(dir)
	if not rockspecPath then
		return nil, "No *.rockspec found in directory: " .. dir
	end

	local specContent = fs.read(rockspecPath)
	if not specContent then
		return nil, "Could not read rockspec: " .. rockspecPath
	end

	local ok, rockData = rocked.parse(specContent)
	if not ok then ---@cast rockData string
		return nil, "Failed to parse rockspec '" .. rockspecPath .. "': " .. rockData
	end ---@cast rockData rocked.raw.Output

	local name = rockData.package
		or path.basename(rockspecPath):gsub("%-[^%-]+%-[^%-]+%.rockspec$", ""):gsub("%.rockspec$", "")

	local synthConfig = Config.new({
		name = name,
		version = rockData.version or "0.0.0",
	})

	local pkg = setmetatable({ dir = dir }, Package)
	pkg.cachedConfig = synthConfig
	pkg.buildfn = makeRockspecBuildfn(rockData)

	return pkg, nil
end

return openRocks
